export const ROUTE_NAME = {
  BASE: "/",
  DASHBOARD: "",
  PROFILE: "/profile",
  //Admin routes
  CUSTOMERS: "/customers",
  SERVICE_REQUEST: "/service-request",
  SERVICE_PROVIDER: "/service-provider",
  SERVICE_CATEGORIES: "/service-categories",
  SERVICE: "/service",
  REPORTS: "/reports",

  // User Routes
};

export const ROUTE_DEFINATION = {
  BASE: ROUTE_NAME.BASE,
  DASHBOARD: ROUTE_NAME.DASHBOARD,
  PROFILE: ROUTE_NAME.PROFILE,
  CUSTOMER: ROUTE_NAME.CUSTOMERS,
  SERVICE_REQUEST: ROUTE_NAME.SERVICE_REQUEST,
  SERVICE_PROVIDER: ROUTE_NAME.SERVICE_PROVIDER,
  SERVICE_CATEGORIES: ROUTE_NAME.SERVICE_CATEGORIES,
  SERVICE: ROUTE_NAME.SERVICE,
  REPORTS: ROUTE_NAME.REPORTS,
};
