export const ROUTE_NAME = {
  BASE: "/",
  DASHBOARD: "",
  PROFILE: "/profile",
  SIGNIN: "/signin",
  //Admin routes
  ALL_SERVICE_LIST: "/all-service-list",
  ALL_USER_LIST: "all-user-list",
  ALL_SERVICE_REQUEST: "all-service-request",
  CREATE_CATEGORY: "create-category",
  CREATE_SUB_CATEGORY: "create-sub-category",
  CREATE_SERVICE: "create-service",
  SERVICE_PROVIDER_LIST: "service-provide-list",
  SERVICE: "/service",
  // User Routes
};

export const ROUTE_DEFINATION = {
  BASE: ROUTE_NAME.BASE,
  DASHBOARD: ROUTE_NAME.DASHBOARD,
  SIGNIN: ROUTE_NAME.SIGNIN,
  ALL_SERVICE_LIST: ROUTE_NAME.ALL_SERVICE_LIST,
  ALL_USER_LIST: ROUTE_NAME.ALL_USER_LIST,
  ALL_SERVICE_REQUEST: ROUTE_NAME.ALL_SERVICE_REQUEST,
  CREATE_CATEGORY: ROUTE_NAME.CREATE_CATEGORY,
  CREATE_SUB_CATEGORY: ROUTE_NAME.CREATE_SUB_CATEGORY,
  CREATE_SERVICE: ROUTE_NAME.CREATE_SERVICE,
  SERVICE_PROVIDER_LIST: ROUTE_NAME.SERVICE_PROVIDER_LIST,
  SERVICE: ROUTE_NAME.SERVICE,
};
